MultiModalPredictor:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      presets:
        __has_values: true
        __dtype: str
        __values:
          - best_quality
          - high_quality
          - medium_quality
        __user_mapping: preset
        __hint: Preset for the quality of the model. Higher quality models take longer to train.
    fit:
      time_limit:
        __has_values: false
        __dtype: int
        __user_mapping: time_limit
        __hint: Time limit for the experiment in seconds
      __extra_args:
        hyperparameter_tune_kwargs:
            __dtype: dict
            num_trials:
                __has_values: false
                __dtype: int
                __user_mapping: num_trials
                __hint: Number of different models to try

    predict:
      candidate_data:
        __has_values: false
        __dtype: list
        __user_mapping: zero_shot_targets
        __hint: List of candidates for the model to predict on

TabularPredictor:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      eval_metric:
        __has_values: false
        __dtype: str
        __user_mapping: eval_metric
        __hint: Metric to use for evaluation
    fit:
      time_limit:
        __has_values: false
        __dtype: int
        __user_mapping: time_limit
        __hint: Time limit for the experiment in seconds
      presets:
        __has_values: true
        __dtype: str
        __values:
          - best_quality
          - high_quality
          - good_quality
          - medium_quality
          - optimize_for_deployment
          - interpretable
          - ignore_text
        __user_mapping: preset
        __hint: Preset for the quality of the model. Higher quality models take longer to train.
      __extra_args:
        hyperparameter_tune_kwargs:
            __dtype: dict
            num_trials:
                __has_values: false
                __dtype: int
                __user_mapping: num_trials
                __hint: Number of different models to try

TimeSeriesPredictor:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_mappings:
    constructor:
      prediction_length:
        __has_values: false
        __dtype: int
        __user_mapping: prediction_length
        __hint: Number of time steps to predict into the future
      eval_metric:
        __has_values: true
        __dtype: str
        __values:
          - mean_wQuantileLoss
          - MAPE
          - sMAPE
          - MASE
          - MSE
          - RMSE
        __user_mapping: eval_metric
        __hint: Metric to use for evaluation
    fit:
      time_limit:
        __has_values: false
        __dtype: int
        __user_mapping: time_limit
        __hint: Time limit for the experiment in seconds
      presets:
        __has_values: true
        __dtype: str
        __values:
          - best_quality
          - high_quality
          - medium_quality
          - fast training
        __user_mapping: preset
        __hint: Preset for the quality of the model. Higher quality models take longer to train.
      __extra_args:
        hyperparameter_tune_kwargs:
            __dtype: dict
            num_trials:
                __has_values: false
                __dtype: int
                __user_mapping: num_trials
                __hint: Number of different models to try

