MultiModalPredictor:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      presets:
        __has_values: true
        __dtype: str
        __values:
          - best_quality
          - high_quality
          - medium_quality
        __user_mapping: preset
    fit:
      time_limit:
        __has_values: false
        __dtype: int
        __user_mapping: time_limit
      __extra_args:
        hyperparameter_tune_kwargs:
            __dtype: dict
            num_trials:
                __has_values: false
                __dtype: int
                __user_mapping: num_trials
    predict:
      candidate_data:
        __has_values: false
        __dtype: list
        __user_mapping: zero_shot_targets

TabularPredictor:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      eval_metric:
        __has_values: false
        __dtype: str
        __user_mapping: eval_metric
    fit:
      time_limit:
        __has_values: false
        __dtype: int
        __user_mapping: time_limit
      presets:
        __has_values: true
        __dtype: str
        __values:
          - best_quality
          - high_quality
          - good_quality
          - medium_quality
          - optimize_for_deployment
          - interpretable
          - ignore_text
        __user_mapping: preset
      __extra_args:
        hyperparameter_tune_kwargs:
            __dtype: dict
            num_trials:
                __has_values: false
                __dtype: int
                __user_mapping: num_trials

TimeSeriesPredictor:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_mappings:
    constructor:
      prediction_length:
        __has_values: false
        __dtype: int
        __user_mapping: prediction_length
      eval_metric:
        __has_values: true
        __dtype: str
        __values:
          - mean_wQuantileLoss
          - MAPE
          - sMAPE
          - MASE
          - MSE
          - RMSE
        __user_mapping: eval_metric
    fit:
      time_limit:
        __has_values: false
        __dtype: int
        __user_mapping: time_limit
      presets:
        __has_values: true
        __dtype: str
        __values:
          - best_quality
          - high_quality
          - medium_quality
          - fast training
        __user_mapping: preset
      __extra_args:
        hyperparameter_tune_kwargs:
            __dtype: dict
            num_trials:
                __has_values: false
                __dtype: int
                __user_mapping: num_trials

