AutoSklearnClassifier:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      time_left_for_this_task:
        __has_values: false
        __dtype: int
        __user_mapping: time_limit
        __hint: Time limit for the experiment in seconds
      n_jobs:
        __has_values: false
        __dtype: int
        __user_mapping: n_jobs
        __hint: Number of parallel jobs to run
      memory_limit:
        __has_values: false
        __dtype: int
        __user_mapping: memory_limit
        __hint: Memory limit for each model in MB
      metric:
        __has_values: true
        __values:
          - accuracy
          - balanced_accuracy
          - f1
          - f1_weighted
          - roc_auc
          - precision
          - average_precision
          - recall
          - log_loss
        __dtype: str
        __user_mapping: evaluation_metric
        __hint: Metric to use for training and validation
      __extra_args:
        ensemble_kwargs:
          __dtype: dict
          ensemble_size:
            __has_values: false
            __dtype: int
            __user_mapping: ensemble_size
            __hint: Number of models to include in the ensemble
     

AutoSklearnRegressor:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      time_left_for_this_task:
        __has_values: false
        __dtype: int
        __user_mapping: time_limit
        __hint: Time limit for the experiment in seconds
      n_jobs:
        __has_values: false
        __dtype: int
        __user_mapping: n_jobs
        __hint: Number of parallel jobs to run
      memory_limit:
        __has_values: false
        __dtype: int
        __user_mapping: memory_limit
        __hint: Memory limit for each model in MB
      metric:
        __has_values: true
        __values:
          - r2
          - mean_squared_error
          - mean_absolute_error
          - median_absolute_error
        __dtype: str
        __user_mapping: evaluation_metric
        __hint: Metric to use for training and validation
      __extra_args:
        ensemble_kwargs:
          __dtype: dict
          ensemble_size:
            __has_values: false
            __dtype: int
            __user_mapping: ensemble_size    
            __hint: Number of models to include in the ensemble