AutoSklearnClassifier:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      time_left_for_this_task:
        __has_values: false
        __dtype: int
        __user_mapping: time_limit
      n_jobs:
        __has_values: false
        __dtype: int
        __user_mapping: n_jobs
      memory_limit:
        __has_values: false
        __dtype: int
        __user_mapping: memory_limit
      __extra_args:
        ensemble_kwargs:
          __dtype: dict
          ensemble_size:
            __has_values: false
            __dtype: int
            __user_mapping: ensemble_size
     

AutoSklearnRegressor:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      time_left_for_this_task:
        __has_values: false
        __dtype: int
        __user_mapping: time_limit
      n_jobs:
        __has_values: false
        __dtype: int
        __user_mapping: n_jobs
      memory_limit:
        __has_values: false
        __dtype: int
        __user_mapping: memory_limit
      __extra_args:
        ensemble_kwargs:
          __dtype: dict
          ensemble_size:
            __has_values: false
            __dtype: int
            __user_mapping: ensemble_size    
