ImageClassifier:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      max_trials:
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
      max_model_size:
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs

ImageRegressor:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
      max_model_size:
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
    fit:
      epochs: 
        __has_values: false
        __dtype: int,
        __user_mapping: epochs

TextClassifier:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
      max_model_size: 
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs

TextRegressor:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
      max_model_size: 
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs

StructuredDataClassifier:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
      max_model_size: 
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs

StructuredDataRegressor:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
      max_model_size: 
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs

TimeseriesForecaster:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
      max_model_size: 
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs