ImageClassifier:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      max_trials:
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
        __hint: Number of different models to try
      max_model_size:
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
        __hint: Maximum size of the model in bytes
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs
        __hint: Number of epochs to train each model

ImageRegressor:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
        __hint: Number of different models to try
      max_model_size:
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
        __hint: Maximum size of the model in bytes
    fit:
      epochs: 
        __has_values: false
        __dtype: int,
        __user_mapping: epochs
        __hint: Number of epochs to train each model

TextClassifier:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
        __hint: Number of different models to try
      max_model_size: 
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
        __hint: Maximum size of the model in bytes
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs
        __hint: Number of epochs to train each model

TextRegressor:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
        __hint: Number of different models to try
      max_model_size: 
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
        __hint: Maximum size of the model in bytes
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs
        __hint: Number of epochs to train each model

StructuredDataClassifier:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
        __hint: Number of different models to try
      max_model_size: 
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
        __hint: Maximum size of the model in bytes
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs
        __hint: Number of epochs to train each model

StructuredDataRegressor:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
        __hint: Number of different models to try
      max_model_size: 
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
        __hint: Maximum size of the model in bytes
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs
        __hint: Number of epochs to train each model

TimeseriesForecaster:
  __mlflow:
    __log_model_type: pyfunc
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
        __hint: Number of different models to try
      max_model_size: 
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
        __hint: Maximum size of the model in bytes
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs
        __hint: Number of epochs to train each model