ImageClassifier:
  __data_types:
    image:
      __task_type:
        classification:
          __problem_types:
            - binary
            - multiclass
            - multilabel
  __hyperparameter_details:
    constructor:
      max_trials:
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
      max_model_size:
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs
ImageRegressor:
  __data_types:
    image:
      __task_type:
        regression:
          __problem_types:
            - regression
            - multioutput
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
      max_model_size:
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
    fit:
      epochs: 
        __has_values: false
        __dtype: int,
        __user_mapping: epochs
TextClassifier:
  __data_types:
    text:
      __task_type:
        classification:
          __problem_types:
            - binary
            - multiclass
            - multilabel
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
      max_model_size: 
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs
TextRegressor:
  __data_types:
    text:
      __task_type:
        regression:
          __problem_types:
            - regression
            - multioutput
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
      max_model_size: 
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs
StructuredDataClassifier:
  __data_types:
    tabular:
      __task_type:
        classification:
          __problem_types:
            - binary
            - multiclass
            - multilabel
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
      max_model_size: 
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs
StructuredDataRegressor:
  __data_types:
    tabular:
      __task_type:
        regression:
          __problem_types:
            - regression
            - multioutput
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
      max_model_size: 
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs

TimeseriesForecaster:
  __data_types:
    time_series:
      __task_type:
        forecast:
          __problem_types:
            - forecast
  __hyperparameter_details:
    constructor:
      max_trials: 
        __has_values: false
        __dtype: int
        __user_mapping: num_trials
      max_model_size: 
        __has_values: false
        __dtype: int
        __user_mapping: max_model_size
    fit:
      epochs: 
        __has_values: false
        __dtype: int
        __user_mapping: epochs